### ISSUE TITLE
Could not find com.zoho.salesiq:mobilisten:8.0.5.

### ISSUE THREAD

**Issue by Tarun24RN** [zoho/SalesIQ-Mobilisten-ReactNative#104] opened 2024-10-01 11:11 UTC
Could not determine the dependencies of task ':app:mergeDevelopmentDebugNativeLibs'.
> Could not resolve all task dependencies for configuration ':app:developmentDebugRuntimeClasspath'.
   > Could not find com.zoho.salesiq:mobilisten:8.0.5.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/zoho/salesiq/mobilisten/8.0.5/mobilisten-8.0.5.pom
       - https://repo.maven.apache.org/maven2/com/zoho/salesiq/mobilisten/8.0.5/mobilisten-8.0.5.pom
       - file:/Users/tarunsharma/Documents/Ripenapps_Project/InstaQuit/qs_6.9_clone/QSApp2022/node_modules/jsc-android/dist/com/zoho/salesiq/mobilisten/8.0.5/mobilisten-8.0.5.pom
       - https://dl.google.com/dl/android/maven2/com/zoho/salesiq/mobilisten/8.0.5/mobilisten-8.0.5.pom
       - https://www.jitpack.io/com/zoho/salesiq/mobilisten/8.0.5/mobilisten-8.0.5.pom
     Required by:
         project :app
         project :app > project :react-native-zohosalesiq-mobilisten

**Comment by bhahirathan-mb-11956** [comment] 2024-10-01 12:04
Duplicate of #86, #66 .

**Closed by bhahirathan-mb-11956** 2024-10-01 12:04 UTC

**Comment by Tarun24RN** [comment] 2024-10-03 04:43
repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.zohodl.com' }
    }
    I have put url in the repositories object, there is no such code which you have provided in your earlier solutions
    allprojects {
    repositories {
             ....
             maven { url 'https://maven.zohodl.com' }
             ....
    }
}
in my build.gradle.

**Comment by bhahirathan-mb-11956** [comment] 2024-10-03 11:24
Hi @Tarun24RN
 
Since Gradle 7.0, it's recommended to use the dependencyResolutionManagement block in settings.gradle for managing project dependencies.
 
1. So if your project uses `android/settings.gradle`, please use the below sample snippet:
```dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Add the Zoho Maven URL here
        maven { url 'https://maven.zohodl.com' }
    }
}
```

Else if your project uses `android/build.gradle`, please use the below sample snippet:
```
buildscript {
      // Define classpath dependencies or plugins
}
allprojects {
    repositories {
      // Default repositories for dependencies
      google()
      mavenCentral()
      // Add the Zoho Maven URL here
      maven { url 'https:/
        /maven.zohodl.com' }
      
    }
}
```
 
I hope this helps. If you have any other queries, please write us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com). We will be happy to help with this case.
