### ISSUE TITLE
Query: Build errors on simulator (Xcode 11.7)

### ISSUE THREAD

**Issue by sangitahirani** [zoho/SalesIQ-Mobilisten-ReactNative#14] opened 2021-04-07 11:06 UTC
Hi,

I am having build errors in iOS in xcode 11.7 . I have tried solving them , solutions given by your team but all in vain .

I have attached screenshot of errors . Please solve this ASAP

Thanks
![Screen Shot 2021-04-07 at 4 35 50 PM](https://user-images.githubusercontent.com/76580092/113856800-57a65b80-97bf-11eb-9d02-d19d233f7573.png)

**Comment by Rishabh-Raghunath** [comment] 2021-04-07 11:17
Hi @sangitahirani,
Could you let us know the version of the react-native package you are using? 
We would also like to know if this error occurs if the app is built with a real device selected rather than the simulator.

**Comment by sangitahirani** [comment] 2021-04-07 11:19
react-native : 0.63.1
"react-native-zohosalesiq-mobilisten": "^2.0.0" (also tried with 1.4.2)

This error is occurring in simulator

**Comment by Rishabh-Raghunath** [comment] 2021-04-07 11:21
Could you help us with us a screenshot of the **Architectures** tab within the app's project setting in Xcode?

**Comment by sangitahirani** [comment] 2021-04-07 11:24
![Screen Shot 2021-04-07 at 4 53 57 PM](https://user-images.githubusercontent.com/76580092/113858881-e0be9200-97c1-11eb-9df4-48cf19f3150f.png)

**Comment by sangitahirani** [comment] 2021-04-07 11:25
Here it is..
![Screen Shot 2021-04-07 at 4 55 22 PM](https://user-images.githubusercontent.com/76580092/113859031-106d9a00-97c2-11eb-9825-f602a9931c89.png)

**Comment by Rishabh-Raghunath** [comment] 2021-04-07 11:52
Do you happen to have "EXCLUDED_ARCHS" set to any value in the project within the build settings?

**Comment by sangitahirani** [comment] 2021-04-07 12:24
hi,
Its working in real device but not in simulator ..

Thanks

**Comment by Rishabh-Raghunath** [comment] 2021-04-07 12:34
Yes, I understand. This is very like an issue in the project build settings while building for the simulator architecture.
Do you happen to have EXCLUDED_ARCHS set to any value within build settings?

**Comment by Rishabh-Raghunath** [comment] 2021-04-09 04:49
@sangitahirani Were you able to find and solve the issue within build settings?

**Comment by sangitahirani** [comment] 2021-04-12 06:58
Hi,
I am not able to find EXCLUDED_ARCHS in build settings . Can u pls help?
Sorry for late reply

Thanks

**Comment by Rishabh-Raghunath** [comment] 2021-04-13 03:09
Hi @sangitahirani, could you try updating Cocoapods to the [latest release](https://github.com/CocoaPods/CocoaPods/releases) and try running the **`pod install`** command again?
If that does not solve your issue, it would be very helpful if you could send us a minimal reproducible example project via Github so we can locate the issue with ease.

**Comment by Rishabh-Raghunath** [comment] 2021-04-26 04:05
@sangitahirani We are closing this issue since the same could not be replicated by us and because it has not had recent activity.
If you were unable to locate the issue within the build settings, please reopen the same by attaching an [MWE](https://stackoverflow.com/help/minimal-reproducible-example) project that demonstrates the behavior to help us investigate further.

Thank you for your contributions.

**Closed by Rishabh-Raghunath** 2021-04-26 04:05 UTC
Labels: awaiting user input, duplicate
