### ISSUE TITLE
got error  on production environment "Attempt to invoke interface method 'boolean android.content.SharedPreferences.getBoolean(java.lang.String, boolean)' on a null object reference" 

### ISSUE THREAD

**Issue by hungkoala** [zoho/SalesIQ-Mobilisten-ReactNative#36] opened 2021-12-15 03:24 UTC
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{care.zoop.bewell/com.zoho.livechat.android.ui.activities.ChatActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.getBoolean(java.lang.String, boolean)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3827)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4003)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by Angu-G** [comment] 2021-12-16 17:53
Hello @hungkoala, Please upgrade to our latest [version(v4.2.4)](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v4.2.4) and let us know.

**Comment by Angu-G** [comment] 2021-12-28 14:21
Hi @hungkoala, We hope this error does not reproduce with our latest version. We are closing this issue now since we don't have any recent activities. You can get back to us for future queries.

**Closed by Angu-G** 2021-12-28 14:21 UTC
Labels: awaiting user input
